# CREATE DATABASE CECYTEM;
# USE CECYTEM;
DROP TABLE IF EXISTS TBL_HORARIO;
DROP TABLE IF EXISTS TBL_MATERIA;
DROP TABLE IF EXISTS TBL_GRUPO;
DROP TABLE IF EXISTS TBL_SALON;
DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER(
  INT_USER INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VCH_NAME VARCHAR(45) DEFAULT NULL,
  VCH_A_PATERNO VARCHAR(45) DEFAULT NULL,
  VCH_A_MATERNO VARCHAR(45) DEFAULT NULL,
  TXT_HORARIO TEXT DEFAULT NULL,
  INT_NUM_NOMINA INT(11) DEFAULT NULL,
  ENM_ESTADO_CIVIL ENUM('SOLTER@','CASAD@','VIUD@','DIVORCIAD@') DEFAULT 'SOLTER@',
  ENM_GENERO ENUM('Masculino','Femenino'),
  VCH_LUGAR_NACIMIENTO VARCHAR(45) DEFAULT NULL,
  DDT_NACIMIENTO DATE DEFAULT NULL,
  VCH_CURP VARCHAR(45) DEFAULT NULL,
  VCH_RFC VARCHAR(45) DEFAULT NULL,
  VCH_CORREO VARCHAR(45) DEFAULT NULL,
  DDT_FECHA_INI_ORG DATE DEFAULT NULL,
  VCH_NOMBRAMIENTO VARCHAR(45) DEFAULT NULL,
  ENM_STATUS ENUM('ACTIVO','INACTIVO') DEFAULT 'INACTIVO' ,
  INT_HORAS_BASE INT(11) UNSIGNED DEFAULT NULL,
  INT_HORAS_ADICIONALES INT(11) UNSIGNED DEFAULT NULL,
  VCH_LICENCIATURA VARCHAR(45) DEFAULT NULL,
  VCH_CEDULA_LICENCIATURA VARCHAR(45) DEFAULT NULL,
  VCH_MAESTRIA VARCHAR(45) DEFAULT NULL,
  VCH_CEDULA_MAESTRIA VARCHAR(45) DEFAULT NULL,
  VCH_DOCTORADO VARCHAR(45) DEFAULT NULL,
  VCH_CEDULA_DOCTORADO VARCHAR(45) DEFAULT NULL,
  VCH_CP VARCHAR(45) DEFAULT NULL,
  VCH_COLONIA VARCHAR(45) DEFAULT NULL,
  VCH_CALLE VARCHAR(45) DEFAULT NULL,
  VCH_NUMERO_CALLE VARCHAR(45) DEFAULT NULL,
  VCH_TEL_LOCAL VARCHAR(45) DEFAULT NULL,
  VCH_TEL_CEL VARCHAR(45) DEFAULT NULL,
  VCH_PASS VARCHAR(45) DEFAULT NULL,
  ENM_PERMISOS ENUM('ADMIN','USER') DEFAULT 'USER'
);

CREATE TABLE TBL_SALON(
  INT_SALON INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VCH_NOMBRE VARCHAR(45) DEFAULT NULL
);

CREATE TABLE TBL_GRUPO(
  INT_GRUPO INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INT_TAMAÑO INT(11) UNSIGNED DEFAULT NULL,
  VCH_ESPACIALIDAD VARCHAR(45) DEFAULT NULL,
  ENM_TURNO ENUM('MATUTINO','MIXTO')
);

CREATE TABLE TBL_MATERIA(
  INT_MATERIA INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VCH_NOMBRE VARCHAR(45) DEFAULT NULL,
  INT_SEMESTRE INT(11) UNSIGNED DEFAULT NULL,
  INT_HORAS_P INT(11) UNSIGNED DEFAULT NULL,
  INT_HORAS_T INT(11) UNSIGNED DEFAULT NULL
);

CREATE TABLE TBL_HORARIO(
  INT_HORARIO INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INT_PROFESOR INT(11) UNSIGNED NOT NULL,
  INT_GRUPO INT(11) UNSIGNED NOT NULL,
  INT_MATERIA INT(11) UNSIGNED NOT NULL,
  INT_SALON INT(11) UNSIGNED NOT NULL,
  VCH_GENERACION VARCHAR(45) DEFAULT NULL,
  VCH_HORARIO VARCHAR(45) DEFAULT NULL,
  FOREIGN KEY (INT_PROFESOR) REFERENCES TBL_USER(INT_USER),
  FOREIGN KEY (INT_GRUPO) REFERENCES TBL_GRUPO(INT_GRUPO),
  FOREIGN KEY (INT_MATERIA) REFERENCES TBL_MATERIA(INT_MATERIA),
  FOREIGN KEY (INT_SALON) REFERENCES TBL_SALON(INT_SALON)
);
