INSERT INTO TBL_USER (INT_USER, VCH_NAME, ENM_GENERO, VCH_CORREO, VCH_PASS, ENM_PERMISOS, ENM_STATUS) VALUES (NULL, "AIME", "Femenino", "a@gmail.com", "123", "ADMIN", "ACTIVO");
INSERT INTO TBL_USER (INT_USER, VCH_NAME, ENM_GENERO, VCH_CORREO, VCH_PASS, ENM_PERMISOS, ENM_STATUS) VALUES (NULL, "ARTURO", "Masculino", "b@gmail.com", "321", "USER", "ACTIVO");
