
#USUARIOS
INSERT INTO TBL_USER (INT_USER, VCH_NAME, ENM_GENERO, VCH_CORREO, VCH_PASS, ENM_PERMISOS, ENM_STATUS) VALUES (NULL, "AIME", "Femenino", "a@gmail.com", "123", "ADMIN", "ACTIVO");
INSERT INTO TBL_USER (INT_USER, VCH_NAME, ENM_GENERO, VCH_CORREO, VCH_PASS, ENM_PERMISOS, ENM_STATUS) VALUES (NULL, "ARTURO", "Masculino", "b@gmail.com", "321", "USER", "ACTIVO");


#SALON
INSERT INTO TBL_SALON VALUES(NULL,"001");
INSERT INTO TBL_SALON VALUES(NULL,"002");
INSERT INTO TBL_SALON VALUES(NULL,"003");
INSERT INTO TBL_SALON VALUES(NULL,"004");
INSERT INTO TBL_SALON VALUES(NULL,"005");
INSERT INTO TBL_SALON VALUES(NULL,"006");

#GRUPO
INSERT INTO TBL_GRUPO VALUES(NULL,"GM01","COMPUTACION","MATUTINO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GM02","ADMINISTRACION","MATUTINO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GM03","MECANICA","MATUTINO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GM04","ELECTRICIDAD","MATUTINO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GX01","COMPUTACION","MIXTO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GX02","ADMINISTRACION","MIXTO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GX03","MECANICA","MIXTO");
INSERT INTO TBL_GRUPO VALUES(NULL,"GX04","ELECTRICIDAD","MIXTO");


#MATERIA

INSERT INTO TBL_MATERIA VALUES(NULL,"FISICA 1",1,10,5);
INSERT INTO TBL_MATERIA VALUES(NULL,"COMPUTACION 2",2,13,5);
INSERT INTO TBL_MATERIA VALUES(NULL,"BIOLOGIA",4,10,5);
INSERT INTO TBL_MATERIA VALUES(NULL,"QUIMICA",5,10,5);
INSERT INTO TBL_MATERIA VALUES(NULL,"ESPAÑOL",6,10,5);



#GENERACION

INSERT INTO TBL_GENERACION VALUES(NULL,"2017-1");
INSERT INTO TBL_GENERACION VALUES(NULL,"2016-2");
INSERT INTO TBL_GENERACION VALUES(NULL,"2016-1");
INSERT INTO TBL_GENERACION VALUES(NULL,"2015-2");
INSERT INTO TBL_GENERACION VALUES(NULL,"2015-1");
